name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm i

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Verify Collection File
      run: ls -l petstore.collection.json

    - name: Run POSTMAN collection
      run: 
        newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      continue-on-error: true

    - name: Output the run details
      uses: actions/upload-artifact@v3
      with:
        name: RunReports
        path: testResults
