name: Run Postman Collection with Newman

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Collection
        run: newman run ./petstore.collection.json --env-var "baseUrl=http://petstore.swagger.io/v2" || exit 0

      - name: Check for Test Failures
        if: failure()
        run: |
          echo "Newman run completed with errors."
          exit 1
